name: M0.153-PAC3
channels:
  - r
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - r-base
  - bioconductor-biostrings
  - bioconductor-complexheatmap
  - bioconductor-genomicfeatures
  - bioconductor-limma
  - bioconductor-deseq2
  - r-proc # per a l'anàlisi de corbes ROC
  - r-car # per a l'anàlisi de residus i altres diagnòstics de models
  - r-caret
  - r-caTools
  - r-dt
  - r-e1071
  - r-kableextra
  - r-kernlab
  - r-knitr
  - r-languageserver
  - r-mlbench
  - r-nortest # per a l'anàlisi de normalitat
  - r-plotly
  - r-shiny
  - r-tidyverse # readr, dplyr, ggplot2, tidyr, etc.
